# Generated by Django 3.0.5 on 2020-04-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tc',
            field=models.IntegerField(default=2),
        ),
    ]
