# Generated by Django 3.0.5 on 2020-04-21 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_typesub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.TypeSub'),
        ),
    ]
